server:
  port: 10086
#数据库连接池配置
spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/qz?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: Yulan1225
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.100.106.192:3306/qz?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: qz
      password: Yulan1225
      hikari:
        minimum-idle: 3
        maximum-pool-size: 10
        max-lifetime: 30000    # 不能小于30秒，否则默认回到1800秒
        connection-test-query: SELECT 1
logging:
    level:
#      com.heuet: DEBUG
      com.xiaoban: INFO